### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by xingheng** [CharlinFeng/CoreList#1]
看到这个方法的签名，我决定不再继续看下去了。强迫症....

+(BOOL)ListModel:(NSArray *)modelArray1 isEqual:(NSArray *)modelArray2

苹果的官方代码规范明确说明不建议把方法的首字母大写，每次看到这种写法我都抓狂。再者，你的这个方法建议改成 - (BOOL)isEqual:(NSArray *)anotherModelArray; 更明了。

某种程度上讲，从一个人的代码风格的细节中可以看出一个人的经验，只是在这里提个意见，不要介意~

No specified issue here, please close it directly.

**Comment by PonyCui** [comment]
确实很多代码都不符合代码规范，希望注意一下吧
